In [2]:
import numpy as np

def branch_and_bound(c, A, b):
    fixed = []
    for i in range(0,len(c)):
        fixed.append(-1)
    def solve_lp(c, A, b,fixed):
        global count
        count += 1
        temp = c/A
        x = np.zeros(len(c))
        if sum(A*np.ones(len(A))) < b[0]:
            return False
        for i in range(0,len(x)):
            if fixed[i] == 0:
                x[i] = 0
            if fixed[i] == 1:
                x[i] = 1
        if sum(x*A)>b[0]:
            print(x)
            return False
        while True:
            minind = temp.argmin()
            if fixed[minind] == 1 or fixed[minind] == 0:
                temp[minind] = 1000000000
                continue
            p = b-np.sum(A*x)
            p = p[0]
            if p/A[minind] <= 1:
                x[minind] = p/A[minind]
            else:
                x[minind] = 1
            temp[minind] = 1000000000
            if sum(A*x) == b:
                break
        opt = np.sum(c*x)
        return x,opt
    
    def int_check(x):
        for i in x:
            if i%1 != 0:
                return False
        return True


    def branch(c, A, b, fixed):
        res = solve_lp(c, A, b, fixed)
        if res != False:
            if int_check(res[0]):
                return res
            else:
                for i in range(0,len(c)):
                    if res[0][i]%1 != 0:
                        non_int_index = i
                        break 
                fixed[non_int_index] = 0
                res_lower = branch(c, A, b, fixed)
                fixed[non_int_index] = 1
                res_upper = branch(c, A, b, fixed)
                if res_lower == None and res_upper == None:
                    return None
                if res_lower == None:
                    return res_upper
                if res_upper == None:
                    return res_lower
                if res_lower[1] < res_upper[1]:
                    return res_lower
                else:
                    return res_upper
        else:
            return None

    return branch(c, A, b, fixed)
# Example problem
n = 10
k = 5
c = np.ones(n+1)
A = np.ones(n+1)
b = np.array([2*k + 1])

for i in range(0,len(c)-1):
    c[i] = 0
    A[i] = 2


count = 0

res = branch_and_bound(c, A, b)
print(res)
print(count)


[1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0.]
[1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0.]
[1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0.]
[1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
(array([0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1.]), 1.0)
21


In [3]:
l = [1,2,3,4,6]
l.index(max(l))

4